version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend-app
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped